[phases.setup]
nixPkgs = ["python310", "chromium"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install-deps chromium",
    "playwright install chromium"
]

[start]
cmd = "python main.py"
